version: '3.8'

services:
  asterisk-a:
    image: andrius/asterisk:18.11.2-alpine
    container_name: asterisk-a
    volumes:
      - ./asterisk-node-a/configs:/etc/asterisk
      - ./asterisk-node-a/recordings:/var/spool/asterisk/recordings
    ports:
      - "5060:5060/udp"
      - "5038:5038"
    networks:
      - asterisk-net

  asterisk-b:
    image: andrius/asterisk:18.11.2-alpine
    container_name: asterisk-b
    volumes:
      - ./asterisk-node-b/configs:/etc/asterisk
      - ./asterisk-node-b/recordings:/var/spool/asterisk/recordings
    ports:
      - "5061:5060/udp"
      - "5039:5038"
    networks:
      - asterisk-net

networks:
  asterisk-net:
    driver: bridge
