services:
  asterisk-a:
    image: andrius/asterisk
    container_name: asterisk-a
    restart: unless-stopped
    volumes:
      - ./config/asterisk-a:/etc/asterisk
    ports:
      - "5060:5060/udp"                 # SIP (A)
      - "10000-10050:10000-10050/udp"   # RTP (A)
      - "9088:8088"                     # HTTP/WebSocket (A)
      - "5038:5038"                     # AMI (A)
    networks:
      - astnet

  asterisk-b:
    image: andrius/asterisk
    container_name: asterisk-b
    restart: unless-stopped
    volumes:
      - ./config/asterisk-b:/etc/asterisk
    ports:
      - "5160:5060/udp"                 # SIP (B)
      - "11000-11050:10000-10050/udp"   # RTP (B)
      - "9188:8088"                     # HTTP/WebSocket (B)
      - "5138:5038"                     # AMI (B)
    networks:
      - astnet

networks:
  astnet:
    driver: bridge
